### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jkour** [VSoftTechnologies/VSoft.SemanticVersion#1]
Hi,
I have some suggestions for the record/unit.

1. It would be useful to manage SemVer for different platforms. I can imagine something like a Ver Manager with controls version record for each platform

2. You've got a flag IsStable. I think it would be useful to have IsAlpha, IsBeta, IsFinal

3. If there are fields to hold other version info (eg. Company, Copyright, etc.) the record can have a method that generates a resource version file automatically, which is useful for CI purposes (at least on Win)

4. A property can retrieve the build number for the IDE as well

Thanks

**Comment by vincentparrett** [comment]
1. That's outside the scope of what this is intended for, which is just to parse a semantic version string.
2. I think that's best left to the consumer of the library, if they want to attach meaning to the label.
3. Outside the scope of Semantic Version (see the link on the readme). That's what version info is for.
4. Again, totally outdside the scope, this is not a general version info library.
